# Generated by Django 5.0 on 2023-12-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitles',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='subtitles',
            name='start_time',
        ),
    ]
