# Generated by Django 5.0 on 2023-12-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0003_subtitles_end_time_subtitles_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitles',
            name='end_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subtitles',
            name='start_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
