# Generated by Django 5.0 on 2023-12-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0005_video_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uuid',
        ),
    ]
