# Generated by Django 5.0 on 2023-12-17 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0006_remove_video_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
